### ISSUE TITLE
The base[1] always equals -1

### ISSUE THREAD

**Issue by yanwii** [hankcs/AhoCorasickDoubleArrayTrie#13]
According your code, I re-implement the algorithm with c++. 
Because the code of end node equals 0, so, when there is a separate end node, the begin always equals 1(because the code of others word starting at 1, (begin + code) > 1 ), so the base[0 + 1]=-1, it's obviously wrong. 
What's wrong?

**Comment by turbanoff** [comment]
@yanwii No, it's not.
![default](https://user-images.githubusercontent.com/741251/38707996-b279574c-3ebc-11e8-8798-b02f0961b4bb.png)
