### ISSUE TITLE
是否可以实现正向最长匹配

### ISSUE THREAD

**Issue by tonyliangli** [hankcs/AhoCorasickDoubleArrayTrie#16]
您好，
    试用了本项目的双数组AC自动机，比较好用。请问是否能够提供单独的最长匹配方法？
    另外看到HanLP项目com.hankcs.hanlp.collection.trie包中的DoubleArrayTrie.java提供了parseLongestText最长匹配方法，我直接调用可以实现最长匹配。请问该方法是否基于您本项目的双数组AC自动机呢？性能如何？谢谢。

**Comment by hankcs** [comment]
请使用HanLP中的parseLongestText，核心代码与本项目一致。性能与场景有关，需做实验确定。

**Comment by tonyliangli** [comment]
好的，谢谢。
