### ISSUE TITLE
使用此Api进行敏感词过滤

### ISSUE THREAD

**Issue by DaaarksunWang** [hankcs/AhoCorasickDoubleArrayTrie#2]
在网上看到了你的文章,感觉特别厉害, 可我对算法的理解不是很好.

现在我有一个需求跟这个实现有一些差异, 我想稍微改一下, 可不知道如何下手.

需求是:
现在有一串待处理的文字是: "ww_ww" ,需要查找的字符串是:"wwww"

按照现有的逻辑是无法进行匹配的, 我现在的想法是, 能不能针对查找的算法增加一个"字符忽略"的特性,

如在查找过程中,如果遇到指定的字符则认为这个字符符合匹配,让匹配继续下去.

不知道这个想法可行不可行, 如果可行希望能收到你的回复告知下如何下手, = =

**Comment by hankcs** [comment]
匹配的时候 if(c=='_') continue掉，注意++position;

**Comment by DaaarksunWang** [comment]
非常感谢你的回复, 我稍微对源码进行了下修改,增加了字符过滤的特性. :)

https://github.com/DaaarksunWang/AhoCorasickDoubleArrayTrie
