### ISSUE TITLE
StackOverflowError on recursive call 

### ISSUE THREAD

**Issue by tgalery** [hankcs/AhoCorasickDoubleArrayTrie#21]
Hi there and thanks for the awesome library! I use it to generate extra links in a tool that processes a wikipedia xml dump through spark. For each wikipedia page, I'd generate a trie based on all the anchors that can be found in that page. In a specific case, [this line](https://github.com/hankcs/AhoCorasickDoubleArrayTrie/blob/master/src/main/java/com/hankcs/algorithm/AhoCorasickDoubleArrayTrie.java#L977) seems to be recursively called many times and an overflow error is cause.

**Comment by hankcs** [comment]
Could you check the latest patch from @tkuun101 ? 

I'll close this but feel free to reopen it if the issue persists.

**Comment by tgalery** [comment]
Will do
