### ISSUE TITLE
publish a new version to Maven Central?

### ISSUE THREAD

**Issue by cldellow** [hankcs/AhoCorasickDoubleArrayTrie#23]
Hello! Thank you for releasing this library for others to use--it's great!

It looks like the latest version in Maven Central is 1.2.0, which doesn't have https://github.com/hankcs/AhoCorasickDoubleArrayTrie/issues/11. To save people from building master locally, could you publish a new release?

**Comment by hankcs** [comment]
Thanks, done.

**Comment by cldellow** [comment]
thanks!
