### ISSUE TITLE
ArrayIndexOutOfBoundsException, when build with an empty map

### ISSUE THREAD

**Issue by Firstero** [hankcs/AhoCorasickDoubleArrayTrie#45]
![image](https://user-images.githubusercontent.com/68093523/98797569-b6052300-2447-11eb-8809-387229226319.png)

**Comment by hankcs** [comment]
See https://github.com/hankcs/AhoCorasickDoubleArrayTrie/commit/89c7355922790315f8f7a40c9b1657e1fe04df3f
