### ISSUE TITLE
parseText throw ArrayIndexOutOfBoundsException when build with an empty map

### ISSUE THREAD

**Issue by XhstormR** [hankcs/AhoCorasickDoubleArrayTrie#50]
```kotlin
val acdat = AhoCorasickDoubleArrayTrie<String>()
acdat.build(emptyMap())

println(acdat.parseText("uhers")) // java.lang.ArrayIndexOutOfBoundsException
```

![image](https://user-images.githubusercontent.com/10527522/129342845-65522daf-3e64-48ad-81cc-8350addf9b94.png)

**Comment by XhstormR** [comment]
The previous issue https://github.com/hankcs/AhoCorasickDoubleArrayTrie/issues/45  has not been fixed。

**Comment by hankcs** [comment]
Thanks. Now fixed.
