### ISSUE TITLE
调整 matche 类方法参数中的 String 为 CharSequence

### ISSUE THREAD

**Issue by XhstormR** [hankcs/AhoCorasickDoubleArrayTrie#54]
你好，作者，能否将 matche 类方法参数中 String 调整为 CharSequence，以跟 parseText 类方法签名一致。

我在继承 AhoCorasickDoubleArrayTrie 类的时候发现这两类方法需要的字符串类型不一样，所以想调整为一致，不知是有意为之。

![image](https://user-images.githubusercontent.com/10527522/140449306-4c1bf1f5-365b-46f2-a777-76b417c9d45d.png)

**Comment by hankcs** [comment]
CharSequence接口是后面添加的，没注意到这个2接口。已经修改了，谢谢指出
